import type { Product, Supplier } from '../types';

export const mockSuppliers: Supplier[] = [
  {
    id: 'mock1',
    name: 'Örnek Tedarikçi 1',
    website: 'https://example1.com',
    rating: 4.5,
    reliability: 0.95,
  },
  {
    id: 'mock2',
    name: 'Örnek Tedarikçi 2',
    website: 'https://example2.com',
    rating: 4.2,
    reliability: 0.88,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'mock-prod-1',
    name: 'Polyester İplik 150D/48F',
    description: 'Endüstriyel kullanıma uygun yüksek kaliteli polyester iplik',
    category: 'İplik',
    subcategory: 'Polyester',
    supplier: mockSuppliers[0],
    price: 45.50,
    currency: 'TRY',
    unit: 'kg',
    stockStatus: 'in_stock',
    specifications: [
      { key: 'Denye', value: '150D' },
      { key: 'Filament', value: '48F' },
      { key: 'Renk', value: 'Ham' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-2',
    name: 'Pamuk İplik Ne 40/1',
    description: 'Kombine pamuk iplik, örgü ve dokuma için uygundur',
    category: 'İplik',
    subcategory: 'Pamuk',
    supplier: mockSuppliers[0],
    price: 62.00,
    currency: 'TRY',
    unit: 'kg',
    stockStatus: 'in_stock',
    specifications: [
      { key: 'Numara', value: 'Ne 40/1' },
      { key: 'Kompozisyon', value: '%100 Pamuk' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-3',
    name: 'Viskon İplik 30/1',
    description: 'Yüksek kaliteli viskon iplik, dokuma ve triko için ideal',
    category: 'İplik',
    subcategory: 'Viskon',
    supplier: mockSuppliers[1],
    price: 78.90,
    currency: 'TRY',
    unit: 'kg',
    stockStatus: 'low_stock',
    specifications: [
      { key: 'Numara', value: '30/1' },
      { key: 'Parlaklık', value: 'Yarı Mat' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-4',
    name: 'Akrilik İplik 28/2',
    description: 'Yumuşak dokulu akrilik iplik, kazak ve atkı için',
    category: 'İplik',
    subcategory: 'Akrilik',
    supplier: mockSuppliers[1],
    price: 55.00,
    currency: 'TRY',
    unit: 'kg',
    stockStatus: 'in_stock',
    specifications: [
      { key: 'Numara', value: '28/2' },
      { key: 'Büküm', value: 'Çift Bükümlü' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-5',
    name: 'Polyester Kumaş 210T',
    description: 'Su itici özellikli taffeta astar kumaş',
    category: 'Kumaş',
    subcategory: 'Polyester',
    supplier: mockSuppliers[0],
    price: 32.50,
    currency: 'TRY',
    unit: 'm',
    stockStatus: 'in_stock',
    specifications: [
      { key: 'Gramaj', value: '65 gsm' },
      { key: 'Genişlik', value: '150 cm' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-6',
    name: 'Pamuk Kumaş Poplin',
    description: 'Gömleklik pamuk poplin kumaş',
    category: 'Kumaş',
    subcategory: 'Pamuk',
    supplier: mockSuppliers[0],
    price: 95.00,
    currency: 'TRY',
    unit: 'm',
    stockStatus: 'out_of_stock',
    specifications: [
      { key: 'Gramaj', value: '110 gsm' },
      { key: 'Genişlik', value: '145 cm' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-7',
    name: 'Likralı Kumaş Interlock',
    description: 'Esnek yapılı likralı interlock kumaş',
    category: 'Kumaş',
    subcategory: 'Likra',
    supplier: mockSuppliers[1],
    price: 120.00,
    currency: 'TRY',
    unit: 'm',
    stockStatus: 'in_stock',
    specifications: [
      { key: 'Kompozisyon', value: '%95 Polyester %5 Likra' },
      { key: 'Genişlik', value: '160 cm' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
  {
    id: 'mock-prod-8',
    name: 'Polyester İplik 75D/36F',
    description: 'İnce denye polyester iplik, dikiş için uygundur',
    category: 'İplik',
    subcategory: 'Polyester',
    supplier: mockSuppliers[0],
    price: 38.00,
    currency: 'TRY',
    unit: 'kg',
    stockStatus: 'in_stock',
    specifications: [
      { key: 'Denye', value: '75D' },
      { key: 'Filament', value: '36F' },
    ],
    scrapedAt: new Date(),
    source: 'Mock Data',
    lastUpdated: new Date(),
  },
];

export function getMockProducts(): Product[] {
  return mockProducts;
}
